### ISSUE TITLE
Issue when you configure proxy without password

### ISSUE THREAD

**Issue by pagefaulted** [sschwartzman/logstash-output-newrelic#1]
When you configure a proxy with just a host and port, without username or password, the plugin crashes.

It breaks at line 53,  @proxy_password.value with "nil: value undefined"

**Comment by sschwartzman** [comment]
Thanks for catching that. I've fixed it by adding ":default => "" to line 24. Please try the new version and let me know whether or not it works now.

Thanks,
Seth

**Comment by sschwartzman** [comment]
@pagefaulted any word on this?

**Comment by sschwartzman** [comment]
Assuming it's working now.
